Repository njustesen/botbowl, pull requests merged in 2022-03, with the labels that each got.

#189 Improved installation docs regarding c++ compiler
  docs/cython_development.md
  docs/installation.md
  setup.py
Labels: documentation

#197 New gym env
  botbowl/ai/__init__.py
  botbowl/ai/env.py
  botbowl/ai/env_render.py
  botbowl/ai/layers.py
  botbowl/ai/renderer.py
  botbowl/core/game.py
  botbowl/core/model.py
  botbowl/core/pathfinding/cython_pathfinding.pyx
  botbowl/core/procedure.py
  botbowl/data/formations/11/def_boat.txt
  botbowl/data/saves/my game.bb
  docs/a2c-full.md
  docs/a2c-pathfinding.md
  docs/a2c-selfplay.md
  docs/a2c.md
  docs/gym.md
  examples/a2c/a2c_agent.py
  examples/a2c/a2c_env.py
  examples/a2c/a2c_example.py
  examples/gym_example.py
  examples/multi_gym_example.py
  examples/scripted_bot_example.py
  tests/ai/test_env.py
  tests/framework/test_gym.py
  tests/performance/benchmark_env.py
  tests/performance/benchmark_forward_model.py
Labels: enhancement

#212 Bugfix pathfinding
  botbowl/core/pathfinding/cython_pathfinding.pyx
  botbowl/core/pathfinding/pathing_node.cpp
  botbowl/core/pathfinding/pathing_node.h
  botbowl/core/pathfinding/pathing_node.pxd
  botbowl/core/pathfinding/python_pathfinding.py
  botbowl/core/procedure.py
  tests/ai/test_pathfinding.py
Labels: bug
